<?php
require_once __DIR__ . '/config.php';
require_once __DIR__ . '/plant_config.php';
$token = trim((string)($_GET['token'] ?? ''));
$adminUser = null;
if ($token !== '') {
    $st=$conn->prepare('SELECT * FROM users WHERE auth_token=? LIMIT 1');
    if($st){$st->bind_param('s',$token);$st->execute();$r=$st->get_result();if($r&&$r->num_rows)$adminUser=$r->fetch_assoc();$st->close();}
}
if(!$adminUser||($adminUser['role']??'')!=='admin'){header('Location: index.php');exit;}
$catalog=plant_catalog();
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Solar Plants Admin Dashboard</title><script src="https://cdn.tailwindcss.com"></script><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"><link rel="stylesheet" href="dashboard-ui.css?v=1" data-dashboard-ui><script src="dashboard-ui.js?v=1" defer data-dashboard-ui></script><style>body{font-family:Inter,system-ui,sans-serif}.pulse{animation:p 1.5s infinite}@keyframes p{50%{opacity:.45}}.scroll::-webkit-scrollbar{width:4px}.scroll::-webkit-scrollbar-thumb{background:#cbd5e1;border-radius:4px}</style></head>
<body class="bg-slate-50 text-slate-800 min-h-screen"><nav class="bg-white border-b sticky top-0 z-40"><div class="max-w-7xl mx-auto px-4 sm:px-6 min-h-16 py-2 flex flex-wrap gap-3 justify-between items-center"><div class="flex items-center gap-2 min-w-0"><div class="w-9 h-9 rounded-lg bg-emerald-600 text-white flex items-center justify-center shrink-0"><i class="fa-solid fa-solar-panel"></i></div><div class="min-w-0"><h1 class="font-black truncate">Solar Plants Dashboard</h1><p class="text-[10px] text-slate-500 font-bold">2 POWER PLANTS</p></div></div><div class="flex flex-wrap items-center justify-end gap-2 sm:gap-3"><span id="wsStatus" class="text-xs font-bold text-red-500">Connecting...</span><div class="px-3 py-2 bg-emerald-50 border border-emerald-100 rounded-lg text-xs font-bold whitespace-nowrap">Overall Active: <span id="overall">0.00 kW</span></div><button onclick="openUsers()" class="px-3 py-2 bg-blue-600 text-white rounded-lg text-xs font-bold whitespace-nowrap">Add User</button><button onclick="location.href='logout.php'" class="px-3 py-2 bg-slate-100 rounded-lg text-xs font-bold whitespace-nowrap">Logout</button></div></div></nav>
<main class="max-w-7xl mx-auto p-4 sm:p-6"><div id="cards" class="grid grid-cols-1 lg:grid-cols-2 gap-4 sm:gap-6"></div></main>
<div id="userModal" class="fixed inset-0 hidden bg-slate-900/50 z-50 items-center justify-center p-4"><div class="bg-white rounded-xl p-4 sm:p-6 w-full max-w-md"><div class="flex justify-between items-center gap-3 mb-4"><h2 class="font-black">Add User</h2><button onclick="closeUsers()" aria-label="Close"><i class="fa-solid fa-xmark"></i></button></div><form id="userForm" class="space-y-3"><input id="email" type="email" required placeholder="Email" class="w-full border rounded-lg px-3 py-2"><input id="password" type="password" required minlength="8" placeholder="Password (8+ characters)" class="w-full border rounded-lg px-3 py-2"><select id="plant" class="w-full border rounded-lg px-3 py-2"></select><select id="role" class="w-full border rounded-lg px-3 py-2"><option value="user">User</option><option value="admin">Admin</option></select><button class="w-full bg-emerald-600 text-white rounded-lg py-2 font-bold">Create</button><p id="userMsg" class="text-xs font-bold text-center"></p></form></div></div>
<script>
const plants=<?php echo json_encode(array_values($catalog),JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES); ?>;const token=<?php echo json_encode($token); ?>;const state={},sockets={},reconnect={};
plants.forEach(p=>state[p.id]={vcbPower:0,hasVCB:false,dailyEnergy:0,inverters:{},lastLive:0,lastUpdate:'--'});
function cardHtml(p){return `<a href="home.php?plant=${encodeURIComponent(p.id)}&token=${encodeURIComponent(token)}" class="block h-full"><div class="bg-white border rounded-2xl shadow-sm overflow-hidden h-full min-h-[420px]"><div class="px-4 sm:px-5 py-4 bg-emerald-50 border-b flex justify-between items-start gap-3"><div class="min-w-0"><h2 class="font-black text-base leading-snug">${p.name}</h2><p class="text-[11px] font-bold text-emerald-700 mt-1">Service Number - ${p.service_number}</p></div><span id="badge-${p.id}" class="shrink-0 h-fit px-2 py-1 rounded-full bg-slate-100 text-slate-500 text-[10px] font-black">WAITING</span></div><div class="p-4 sm:p-5 grid grid-cols-1 sm:grid-cols-2 gap-3"><div class="bg-slate-50 border rounded-xl p-4"><p class="text-[10px] font-black uppercase text-slate-400">Live Active Power</p><p id="active-${p.id}" class="text-2xl font-black mt-1">0.00 kW</p><p id="activeSource-${p.id}" class="text-[10px] text-slate-400 mt-1">Inverter fallback</p></div><div class="bg-purple-50/50 border border-purple-100 rounded-xl p-4"><p class="text-[10px] font-black uppercase text-purple-500">Today Energy</p><p id="today-${p.id}" class="text-2xl font-black mt-1">0.00 kWh</p><p class="text-[10px] text-slate-400 mt-1">Live inverter / HT when available</p></div><div class="sm:col-span-2 flex justify-between gap-3 text-xs text-slate-500"><span>Last update</span><span id="time-${p.id}" class="font-bold text-right">--</span></div><div id="inv-${p.id}" class="sm:col-span-2 bg-slate-50 border rounded-xl p-3 min-h-[180px] max-h-[240px] overflow-y-auto scroll"><div class="text-xs text-slate-400 text-center py-10">Waiting for inverter telemetry...</div></div></div></div></a>`}
function renderCards(){document.getElementById('cards').innerHTML=plants.map(cardHtml).join('');const sel=document.getElementById('plant');plants.forEach(p=>sel.add(new Option(p.name,p.id)));}
function invPower(values){for(const [k,v] of Object.entries(values||{})){const x=k.toLowerCase();if(/active.*power|ac.*power|power.*ac|a\.c\..*power/.test(x)&&!/reactive|apparent|3.phase/.test(x))return Number(v)||0}return 0}
function dailyGen(values){for(const [k,v] of Object.entries(values||{}))if(/daily.*generation|daily.*gen/i.test(k))return Number(v)||0;return null}
function stringCount(values){let a=0,t=0;for(const [k,v] of Object.entries(values||{})){const x=k.toLowerCase();if(/phase|3.phase|freq|temp|reactive|apparent|inverter.*curr|total.*curr|grid.*curr|dc.*curr/.test(x))continue;if(/\d/.test(k)&&/curr|current|amp/i.test(k)){t++;if((Number(v)||0)>.5)a++}}return {a,t}}
function finalPower(st){const inv=Object.values(st.inverters).reduce((s,x)=>s+(Number(x.power)||0),0);return st.hasVCB?st.vcbPower:inv}
function updateOverall(){document.getElementById('overall').textContent=Object.values(state).reduce((s,x)=>s+finalPower(x),0).toFixed(2)+' kW'}
function update(id){const st=state[id],pwr=finalPower(st);document.getElementById('active-'+id).textContent=pwr.toFixed(2)+' kW';document.getElementById('activeSource-'+id).textContent=st.hasVCB?'HT/VCB active power':'Combined inverter active power';document.getElementById('today-'+id).textContent=(Number(st.dailyEnergy)||0).toFixed(2)+' kWh';document.getElementById('time-'+id).textContent=st.lastUpdate;const b=document.getElementById('badge-'+id);b.className=`shrink-0 h-fit px-2 py-1 rounded-full text-[10px] font-black ${Date.now()-st.lastLive<20000?'bg-green-100 text-green-700':'bg-amber-100 text-amber-700'}`;b.textContent=Date.now()-st.lastLive<20000?'LIVE':'DB FALLBACK';const box=document.getElementById('inv-'+id),keys=Object.keys(st.inverters).sort();if(keys.length)box.innerHTML=keys.map(k=>{const v=st.inverters[k];return `<div class="flex flex-wrap justify-between items-center gap-2 bg-white border rounded-lg px-3 py-2 mb-2 text-xs"><span class="font-bold min-w-0 break-words">${k}</span><div class="flex flex-wrap gap-3"><span>${(Number(v.power)||0).toFixed(1)} kW</span>${v.total?`<span class="font-bold">${v.active}/${v.total} strings</span>`:''}</div></div>`}).join('');updateOverall()}
function handle(id,d){if(!d||d.unit_id!==id)return;const st=state[id];st.lastLive=Date.now();st.lastUpdate=d.time||new Date().toLocaleTimeString('en-IN');const vals=d.values||{},task=String(d.task||'').toLowerCase(),dev=String(d.device||''),isVCB=task==='vcb'||dev.toLowerCase().includes('vcb');if(isVCB&&vals['3 Phase Active Power']!==undefined){st.vcbPower=Number(vals['3 Phase Active Power'])||0;st.hasVCB=true}const tags=d.virtualTags||{};let tagEnergy=null;for(const [k,v] of Object.entries(tags))if(/vcb.*today|today.*energy/i.test(k)){tagEnergy=Number(typeof v==='object'?v.value:v);break}if(Number.isFinite(tagEnergy)&&tagEnergy>=0)st.dailyEnergy=tagEnergy;const keys=Object.keys(vals),isInv=!isVCB&&(task==='inverter'||dev.toLowerCase().includes('inverter')||keys.some(k=>/active.*power|ac.*power/i.test(k)));if(isInv){const old=st.inverters[dev]||{},sc=stringCount(vals),dg=dailyGen(vals);st.inverters[dev||'Inverter']={power:invPower(vals)||old.power||0,active:sc.t?sc.a:old.active||0,total:sc.t||old.total||0,daily:dg!==null?dg:old.daily||0};if(!(Number.isFinite(tagEnergy)&&tagEnergy>0))st.dailyEnergy=Object.values(st.inverters).reduce((s,x)=>s+(Number(x.daily)||0),0)}update(id)}
function status(){const n=plants.filter(p=>sockets[p.id]&&sockets[p.id].readyState===WebSocket.OPEN).length,el=document.getElementById('wsStatus');el.textContent=n===plants.length?'All Plants Live':`${n}/${plants.length} Live`;el.className='text-xs font-bold '+(n===plants.length?'text-green-600':n?'text-amber-600':'text-red-500 pulse')}
function connect(id){if(sockets[id]&&(sockets[id].readyState===WebSocket.OPEN||sockets[id].readyState===WebSocket.CONNECTING))return;try{const w=new WebSocket('wss://vinobasolar.scadahub.in:5001');sockets[id]=w;w.onopen=()=>{w.send(JSON.stringify({type:'subscribe',unit_id:id}));status()};w.onmessage=e=>{try{handle(id,JSON.parse(e.data))}catch(_){}};w.onclose=()=>{sockets[id]=null;status();clearTimeout(reconnect[id]);reconnect[id]=setTimeout(()=>connect(id),5000)};w.onerror=()=>{}}catch(_){reconnect[id]=setTimeout(()=>connect(id),5000)}}
function indiaDate(){const o={};new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kolkata',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}).formatToParts(new Date()).forEach(x=>{if(x.type!=='literal')o[x.type]=x.value});return {date:`${o.year}-${o.month}-${o.day}`,mins:Number(o.hour)*60+Number(o.minute)}}
async function fallback(id){try{const t=indiaDate(),q=new URLSearchParams({tab:'inv_vcb',type:'daily',date:t.date,plant:id,token});const r=await fetch('api_reports.php?'+q,{cache:'no-store',headers:{Authorization:'Bearer '+token}}),j=await r.json();if(!j.success||!j.data?.length)return;const elapsed=j.data.filter(x=>{const m=String(x.time_label||'').match(/^(\d+):(\d+)/);return m&&Number(m[1])*60+Number(m[2])<=t.mins}),row=elapsed.at(-1)||j.data[0],st=state[id],fresh=Date.now()-st.lastLive<20000,names=j.meta?.inv_names||[];if(!fresh){names.forEach((n,i)=>{const old=st.inverters[n]||{};st.inverters[n]={...old,power:Number(row['inv'+(i+1)+'_kw']||0),daily:Number(row['inv'+(i+1)+'_kwh']||0)}});st.vcbPower=Number(row.vcb_kw||0);st.hasVCB=!!j.meta?.ht_available&&st.vcbPower!==0;st.dailyEnergy=Math.max(0,...elapsed.map(x=>Number(x.inv_total_kwh||0)));st.lastUpdate='DB '+new Date().toLocaleTimeString('en-IN');update(id)}}catch(_){}}
function openUsers(){const m=document.getElementById('userModal');m.classList.remove('hidden');m.classList.add('flex')}function closeUsers(){const m=document.getElementById('userModal');m.classList.add('hidden');m.classList.remove('flex')}
document.getElementById('userForm').addEventListener('submit',async e=>{e.preventDefault();const body={email:document.getElementById('email').value,password:document.getElementById('password').value,plant_id:document.getElementById('plant').value,role:document.getElementById('role').value};const msg=document.getElementById('userMsg');try{const r=await fetch('api.php?action=add_user',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+token},body:JSON.stringify(body)}),j=await r.json();msg.textContent=j.message||j.status;msg.className='text-xs font-bold text-center '+(j.status==='success'?'text-green-600':'text-red-600');if(j.status==='success')e.target.reset()}catch(_){msg.textContent='Unable to create user';msg.className='text-xs font-bold text-center text-red-600'}});
renderCards();plants.forEach(p=>{connect(p.id);fallback(p.id)});setInterval(()=>plants.forEach(p=>fallback(p.id)),15000);status();
</script></body></html>
