<?php
require 'check_auth.php';
require_once __DIR__ . '/plant_config.php';
$currentPlantId = normalize_plant_id($_GET['plant'] ?? ($user['plant_id'] ?? 'vinoba-1'));
if (!is_valid_plant_id($currentPlantId)) $currentPlantId = 'vinoba-1';
$plantInfo = plant_info($currentPlantId) ?? plant_catalog()['vinoba-1'];
?>
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0">
<title><?php echo htmlspecialchars($plantInfo['name']); ?> - Overview</title>
<script src="https://cdn.tailwindcss.com"></script>
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
<script src="sidebar-control.js?v=4" defer></script>
</head>
<body class="h-full bg-slate-50 text-slate-800 font-sans">
<div class="min-h-screen flex relative">
<div id="overlay" class="fixed inset-0 bg-slate-900/40 hidden z-30 md:hidden"></div>
<div id="sidebar-container"></div>
<main class="flex-1 flex flex-col w-full md:ml-64 overflow-x-hidden">
<header class="bg-white p-4 sm:px-6 flex justify-between items-center sticky top-0 z-20 border-b border-slate-200 shadow-sm">
<div class="flex items-center gap-3">
<?php if (($user['role'] ?? '') === 'admin') { ?><a href="admin.php?token=<?php echo urlencode($_GET['token'] ?? ''); ?>" class="flex items-center gap-2 px-3 h-9 rounded-lg bg-slate-100 hover:bg-slate-200 text-slate-700"><i class="fa-solid fa-arrow-left"></i><span class="text-sm font-bold hidden sm:inline">Dashboard</span></a><?php } ?>
<button id="menuBtn" class="md:hidden text-emerald-600 text-2xl">&#9776;</button>
<div><h2 class="text-xl font-black text-slate-800 tracking-tight">Live Plant Telemetry</h2><p class="text-[11px] text-slate-500 font-semibold" id="serviceHeader">Service Number - <?php echo htmlspecialchars($plantInfo['service_number']); ?></p></div>
</div>
<div class="flex items-center gap-3 bg-slate-50 px-3 py-1.5 rounded-lg border border-slate-100"><div id="refreshPulse" class="w-2.5 h-2.5 bg-slate-400 rounded-full"></div><span id="clockDisplay" class="text-xs font-bold text-slate-600 tracking-widest hidden sm:inline">--:--:--</span></div>
</header>
<div class="p-4 sm:p-6 w-full flex flex-col gap-6 max-w-[1600px] mx-auto">
<div class="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-4 gap-4 sm:gap-6">
<div class="bg-white rounded-xl shadow-sm border border-slate-200 p-5"><h3 class="text-[10px] font-black text-slate-400 uppercase tracking-widest mb-2">Plant Profile</h3><p id="profileName" class="font-black text-slate-800 text-lg leading-tight"><?php echo htmlspecialchars($plantInfo['name']); ?></p><div class="flex items-baseline gap-2 mt-2"><p class="font-black text-emerald-600 text-2xl"><?php echo htmlspecialchars((string)$plantInfo['capacity']); ?> <span class="text-sm">MW</span></p><p class="text-xs text-slate-500 border-l pl-2"><?php echo htmlspecialchars($plantInfo['location']); ?></p></div><p class="text-[11px] text-emerald-700 font-bold mt-2">Service Number - <?php echo htmlspecialchars($plantInfo['service_number']); ?></p></div>
<div class="bg-white rounded-xl shadow-sm border border-slate-200 p-5"><h3 class="text-[10px] font-black text-slate-400 uppercase tracking-widest mb-2">Today Energy</h3><p class="font-black text-slate-800 text-3xl" id="vcb_etoday">-- <span class="text-sm font-bold text-purple-600">kWh</span></p><p id="energySource" class="text-xs text-slate-500 mt-1">Waiting for inverter telemetry</p></div>
<div class="bg-white rounded-xl shadow-sm border border-slate-200 p-5"><h3 class="text-[10px] font-black text-slate-400 uppercase tracking-widest mb-2">Live Active Power</h3><p class="font-black text-slate-800 text-3xl" id="vcb_active">-- <span class="text-sm font-bold text-blue-600">kW</span></p><p class="text-xs text-slate-500 mt-1">Peak Today: <span id="vcb_peak" class="font-bold">--</span> kW</p><p id="powerSource" class="text-[10px] text-slate-400 mt-1">Combined inverter power</p></div>
<div class="bg-white rounded-xl shadow-sm border border-slate-200 p-5"><h3 class="text-[10px] font-black text-slate-400 uppercase tracking-widest mb-3">Weather</h3><div class="space-y-2 text-sm"><div class="flex justify-between"><span>Radiation</span><strong><span id="wmos_rad">--</span> W/m²</strong></div><div class="flex justify-between"><span>Panel Temp</span><strong><span id="wmos_ptemp">--</span> °C</strong></div><div class="flex justify-between"><span>Wind Speed</span><strong><span id="wmos_wind">--</span> m/s</strong></div></div></div>
</div>
<div class="bg-white rounded-xl shadow-sm border border-slate-200 p-5">
<div class="flex flex-wrap items-center justify-between gap-3 mb-4"><div><h3 class="text-sm font-black text-slate-600 uppercase tracking-widest">Generation Window</h3><p class="text-xs text-slate-500">Database history plus live updates</p></div><span id="htAvailability" class="text-[10px] font-bold rounded-full bg-slate-100 text-slate-500 px-3 py-1">HT DATA OPTIONAL</span></div>
<div class="grid grid-cols-1 md:grid-cols-3 gap-4">
<div class="rounded-xl border bg-blue-50/40 p-4"><p class="text-xs font-black text-blue-700 uppercase">Inverters</p><div class="grid grid-cols-2 gap-3 mt-3"><div><p class="text-[10px] text-slate-400 uppercase">Start</p><p id="inverter_start_time" class="text-xl font-black">--:--</p></div><div><p class="text-[10px] text-slate-400 uppercase">End / Latest</p><p id="inverter_end_time" class="text-xl font-black">--:--</p></div></div></div>
<div class="rounded-xl border bg-purple-50/40 p-4"><p class="text-xs font-black text-purple-700 uppercase">HT / VCB</p><div class="grid grid-cols-2 gap-3 mt-3"><div><p class="text-[10px] text-slate-400 uppercase">Start</p><p id="vcb_start_time" class="text-xl font-black">--:--</p></div><div><p class="text-[10px] text-slate-400 uppercase">End / Latest</p><p id="vcb_end_time" class="text-xl font-black">--:--</p></div></div></div>
<div class="rounded-xl border bg-orange-50/40 p-4"><p class="text-xs font-black text-orange-700 uppercase">Transformer</p><div class="grid grid-cols-2 gap-3 mt-3"><div><p class="text-[10px] text-slate-400 uppercase">Start</p><p id="transformer_start_time" class="text-xl font-black">--:--</p></div><div><p class="text-[10px] text-slate-400 uppercase">End / Latest</p><p id="transformer_end_time" class="text-xl font-black">--:--</p></div></div></div>
</div></div>
<div class="bg-white rounded-xl shadow-sm border border-slate-200 p-5 h-[400px]"><h3 class="text-sm font-black text-slate-600 uppercase tracking-widest mb-4"><i class="fa-solid fa-chart-line text-blue-500 mr-2"></i>Generation Curve (Today)</h3><div class="relative w-full" style="height:320px"><canvas id="powerChart"></canvas></div></div>
<div class="bg-white rounded-xl shadow-sm border border-slate-200 p-5"><div class="flex justify-between gap-3 items-center border-b pb-3 mb-5"><h3 class="text-sm font-black text-slate-600 uppercase tracking-widest">Inverter Field Array</h3><span id="liveStatus" class="text-xs font-bold text-slate-500">Connecting...</span></div><div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4" id="inv_grid"><div class="text-sm text-slate-400 italic text-center py-8 col-span-full">Waiting for inverter telemetry...</div></div></div>
</div>
</main></div>
<script>
const CURRENT_PLANT=<?php echo json_encode($currentPlantId); ?>;
const PLANT_INFO=<?php echo json_encode($plantInfo, JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES); ?>;
const TOKEN=new URLSearchParams(location.search).get('token')||sessionStorage.getItem('vs_token')||localStorage.getItem('vs_token')||'';
const WS_URL='wss://vinobasolar.scadahub.in:5001';
const state={inverters:{},vcbPower:0,hasVcb:false,vcbToday:null,peakPower:0,lastLive:0};
let ws=null,reconnectTimer=null,apiTimer=null;
function indiaParts(){const o={};new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kolkata',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}).formatToParts(new Date()).forEach(x=>{if(x.type!=='literal')o[x.type]=x.value});return o;}
function indiaDate(){const p=indiaParts();return `${p.year}-${p.month}-${p.day}`;}
function nowMinutes(){const p=indiaParts();return Number(p.hour)*60+Number(p.minute);}
setInterval(()=>document.getElementById('clockDisplay').textContent=new Date().toLocaleTimeString('en-IN',{hour12:false}),1000);
function inverterPower(values){for(const [k,v] of Object.entries(values||{})){const x=k.toLowerCase();if(/active.*power|ac.*power|power.*ac|a\.c\..*power/.test(x)&&!/reactive|apparent|3.phase/.test(x))return Number(v)||0;}return 0;}
function inverterDaily(values){for(const [k,v] of Object.entries(values||{}))if(/daily.*generation|daily.*gen/i.test(k))return Number(v)||0;return null;}
function stringSummary(values){let active=0,total=0;for(const [k,v] of Object.entries(values||{})){const x=k.toLowerCase();if(/phase|3.phase|freq|temp|reactive|apparent|inverter.*curr|total.*curr|grid.*curr|dc.*curr/.test(x))continue;if(/\d/.test(k)&&/curr|current|amp/i.test(k)){total++;if((Number(v)||0)>.5)active++;}}return {active,total};}
function inverterTotalPower(){return Object.values(state.inverters).reduce((s,v)=>s+(Number(v.power)||0),0);}
function inverterTotalEnergy(){return Object.values(state.inverters).reduce((s,v)=>s+(Number(v.daily)||0),0);}
function activePower(){return state.hasVcb?state.vcbPower:inverterTotalPower();}
function todayEnergy(){return state.vcbToday!==null?state.vcbToday:inverterTotalEnergy();}
function render(){const power=activePower(),energy=todayEnergy();state.peakPower=Math.max(state.peakPower,power);document.getElementById('vcb_active').innerHTML=power.toFixed(2)+' <span class="text-sm font-bold text-blue-600">kW</span>';document.getElementById('vcb_etoday').innerHTML=energy.toFixed(2)+' <span class="text-sm font-bold text-purple-600">kWh</span>';document.getElementById('vcb_peak').textContent=state.peakPower.toFixed(2);document.getElementById('powerSource').textContent=state.hasVcb?'HT / VCB active power':'Combined inverter active power';document.getElementById('energySource').textContent=state.vcbToday!==null?'HT / VCB today energy':'Combined inverter daily generation';document.getElementById('htAvailability').textContent=state.hasVcb||state.vcbToday!==null?'HT DATA LIVE':'HT DATA UNAVAILABLE';document.getElementById('htAvailability').className='text-[10px] font-bold rounded-full px-3 py-1 '+(state.hasVcb||state.vcbToday!==null?'bg-emerald-100 text-emerald-700':'bg-slate-100 text-slate-500');renderInverters();updateCurrentChart(power);}
function renderInverters(){const grid=document.getElementById('inv_grid'),keys=Object.keys(state.inverters).sort();if(!keys.length)return;grid.innerHTML=keys.map(name=>{const v=state.inverters[name],good=v.total>0&&v.active>=Math.min(22,v.total),bad=v.total>0&&v.active===0;const cls=good?'border-emerald-200 bg-emerald-50/50':bad?'border-red-200 bg-red-50':'border-slate-200 bg-white';return `<div class="border rounded-xl p-5 ${cls}"><div class="flex justify-between items-start gap-2"><div><p class="text-xs font-bold text-slate-500">${name}</p><p class="font-black text-2xl mt-1">${(v.power||0).toFixed(1)} <span class="text-sm text-blue-600">kW</span></p><p class="text-xs text-purple-600 font-bold mt-1">${(v.daily||0).toFixed(1)} kWh today</p></div><span class="text-[10px] font-bold rounded-full bg-slate-100 px-2 py-1">${v.total?`${v.active}/${v.total} strings`:'LIVE'}</span></div></div>`}).join('');}
const chart=new Chart(document.getElementById('powerChart').getContext('2d'),{type:'line',data:{labels:[],datasets:[{label:'Plant Output (kW)',data:[],borderColor:'#2563eb',backgroundColor:'rgba(37,99,235,.08)',fill:true,tension:.25,pointRadius:2}]},options:{responsive:true,maintainAspectRatio:false,scales:{y:{beginAtZero:true}}}});
function updateCurrentChart(power){const p=indiaParts(),label=`${p.hour}:00`,idx=chart.data.labels.indexOf(label);if(idx>=0){chart.data.datasets[0].data[idx]=power;chart.update('none');}}
function loadChart(rows){if(!Array.isArray(rows))return;const labels=[],data=[];rows.forEach(r=>{if(Number(r.inv_total_kw||0)!==0||Number(r.vcb_kw||0)!==0){labels.push(r.time_label);data.push(Number(r.vcb_kw||0)||Number(r.inv_total_kw||0));}});if(labels.length){chart.data.labels=labels;chart.data.datasets[0].data=data;chart.update('none');}}
function hydrateTimes(meta){const t=meta?.operating_times||{};['inverter','vcb','transformer'].forEach(type=>{const x=t[type]||{};const a=document.getElementById(type+'_start_time'),b=document.getElementById(type+'_end_time');if(a)a.textContent=x.start||'--:--';if(b)b.textContent=x.end||'--:--';});}
function handleLive(d){if(!d||d.unit_id!==CURRENT_PLANT)return;state.lastLive=Date.now();document.getElementById('liveStatus').textContent='LIVE';document.getElementById('liveStatus').className='text-xs font-bold text-emerald-600';const values=d.values||{},task=String(d.task||'').toLowerCase(),device=String(d.device||'').toLowerCase(),isVcb=task==='vcb'||device.includes('vcb');if(isVcb&&values['3 Phase Active Power']!==undefined){state.vcbPower=Number(values['3 Phase Active Power'])||0;state.hasVcb=true;}for(const [k,x] of Object.entries(d.virtualTags||{})){if(/vcb.*today|today.*energy/i.test(k)){const n=Number(typeof x==='object'?x.value:x);if(Number.isFinite(n))state.vcbToday=n;break;}}const isInv=!isVcb&&(task==='inverter'||device.includes('inverter')||Object.keys(values).some(k=>/active.*power|ac.*power/i.test(k)));if(isInv){const name=d.device||'Inverter',old=state.inverters[name]||{},summary=stringSummary(values),daily=inverterDaily(values);state.inverters[name]={power:inverterPower(values)||old.power||0,daily:daily===null?(old.daily||0):daily,active:summary.total?summary.active:(old.active||0),total:summary.total||(old.total||0)};}if(values['raw data']!==undefined)document.getElementById('wmos_rad').textContent=values['raw data'];if(values['pannel temperature']!==undefined)document.getElementById('wmos_ptemp').textContent=values['pannel temperature'];if(values['windspeed']!==undefined)document.getElementById('wmos_wind').textContent=values['windspeed'];render();}
function connect(){if(ws&&(ws.readyState===WebSocket.OPEN||ws.readyState===WebSocket.CONNECTING))return;ws=new WebSocket(WS_URL);ws.onopen=()=>{document.getElementById('refreshPulse').className='w-2.5 h-2.5 bg-emerald-500 rounded-full animate-pulse';ws.send(JSON.stringify({type:'subscribe',unit_id:CURRENT_PLANT}));};ws.onmessage=e=>{try{handleLive(JSON.parse(e.data));}catch(_){}};ws.onclose=()=>{ws=null;document.getElementById('refreshPulse').className='w-2.5 h-2.5 bg-red-500 rounded-full';document.getElementById('liveStatus').textContent='RECONNECTING';clearTimeout(reconnectTimer);reconnectTimer=setTimeout(connect,5000);};}
async function apiFallback(){try{const q=new URLSearchParams({tab:'inv_vcb',type:'daily',date:indiaDate(),plant:CURRENT_PLANT});if(TOKEN)q.set('token',TOKEN);const r=await fetch('api_reports.php?'+q,{cache:'no-store',headers:TOKEN?{Authorization:'Bearer '+TOKEN}:{}}),j=await r.json();if(!j.success||!Array.isArray(j.data))return;hydrateTimes(j.meta);loadChart(j.data);if(Date.now()-state.lastLive<20000)return;const elapsed=j.data.filter(row=>{const m=String(row.time_label||'').match(/^(\d+):(\d+)/);return m&&Number(m[1])*60+Number(m[2])<=nowMinutes();}),row=elapsed.at(-1)||j.data[0],names=j.meta?.inv_names||[];names.forEach((name,i)=>{const old=state.inverters[name]||{};state.inverters[name]={...old,power:Number(row['inv'+(i+1)+'_kw']||0),daily:Number(row['inv'+(i+1)+'_kwh']||0)};});state.hasVcb=!!j.meta?.ht_available;state.vcbPower=Number(row.vcb_kw||0);state.vcbToday=j.meta?.ht_available?Number(row.vcb_kwh||0):null;document.getElementById('liveStatus').textContent='DB FALLBACK';document.getElementById('liveStatus').className='text-xs font-bold text-blue-600';render();}catch(_){}}
fetch('sidebar.html',{cache:'no-store'}).then(r=>r.text()).then(html=>{document.getElementById('sidebar-container').innerHTML=html;document.querySelectorAll('#sidebarNav a').forEach(a=>{let h=a.getAttribute('href');if(!h||h.includes('logout'))return;a.setAttribute('href',`${h}?plant=${encodeURIComponent(CURRENT_PLANT)}&token=${encodeURIComponent(TOKEN)}`);});const pn=document.getElementById('sidebarPlantName');if(pn)pn.textContent=PLANT_INFO.name;if(typeof initSidebar==='function')initSidebar();const o=document.getElementById('overlay'),s=document.getElementById('sidebar');document.getElementById('menuBtn')?.addEventListener('click',()=>{s?.classList.remove('-translate-x-full');o?.classList.remove('hidden');});document.getElementById('closeSidebarBtn')?.addEventListener('click',()=>{s?.classList.add('-translate-x-full');o?.classList.add('hidden');});o?.addEventListener('click',()=>{s?.classList.add('-translate-x-full');o.classList.add('hidden');});});
connect();apiFallback();apiTimer=setInterval(apiFallback,15000);
</script>
</body></html>
