<?php
require_once __DIR__ . '/check_auth.php';
require_once __DIR__ . '/plant_config.php';
$catalog = plant_catalog();
$plants = array_values($catalog);
$userRole = $user['role'] ?? 'user';
$userPlant = normalize_plant_id($user['plant_id'] ?? '');
$requested = trim((string)($_GET['plant'] ?? ''));
$selectedPlant = $userRole === 'admin' ? ($requested === 'all' ? 'all' : normalize_plant_id($requested)) : $userPlant;
if ($selectedPlant !== 'all' && !isset($catalog[$selectedPlant])) $selectedPlant = 'vinoba-1';
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>System Reports</title><script src="https://cdn.tailwindcss.com"></script><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"><script src="sidebar-control.js?v=4" defer></script><script src="https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.10.1/html2pdf.bundle.min.js"></script>
<style>body{font-family:Inter,system-ui,sans-serif}.wrap{overflow-x:auto}.tbl{border-collapse:collapse;min-width:1000px;width:100%}.tbl th,.tbl td{padding:6px 7px;text-align:center;white-space:nowrap;border-bottom:1px solid #e2e8f0;font-variant-numeric:tabular-nums}.tbl th{font-size:10px;text-transform:uppercase;background:#f8fafc;color:#475569}.tbl td{font-size:11px}.pdf-mode .wrap{overflow:visible}.status-dot{width:8px;height:8px;border-radius:9999px;display:inline-block}</style></head>
<body class="bg-slate-50 text-slate-800"><div class="min-h-screen flex"><div id="overlay" class="fixed inset-0 bg-slate-900/40 hidden z-30 md:hidden"></div><div id="sidebar-container"></div><main class="flex-1 md:ml-64 w-full overflow-x-hidden">
<header class="sticky top-0 z-20 bg-white border-b px-4 sm:px-6 py-4 flex justify-between items-center"><div class="flex items-center gap-3"><button id="menuBtn" class="md:hidden text-emerald-700 text-2xl">&#9776;</button><div><h1 class="text-xl font-black">System Reports</h1><p class="text-xs text-slate-500">Two-plant SCADA reports</p></div></div><div class="flex gap-2"><button onclick="exportPDF()" class="px-3 py-2 bg-red-600 text-white rounded-lg text-sm font-bold"><i class="fa-solid fa-file-pdf mr-1"></i>PDF</button><button id="jsonBtn" onclick="downloadJson()" disabled class="px-3 py-2 bg-emerald-600 text-white rounded-lg text-sm font-bold opacity-50">JSON</button></div></header>
<section class="p-4 sm:p-6 max-w-[1700px] mx-auto space-y-5"><div class="bg-white border rounded-xl p-4 flex flex-wrap gap-3 justify-between items-center"><div class="font-bold text-emerald-700"><i class="fa-solid fa-chart-column mr-2"></i>Inverter &amp; HT/VCB Report</div><div class="flex flex-wrap gap-2"><select id="plantSelect" class="border rounded-lg px-3 py-2 text-sm"></select><select id="typeSelect" class="border rounded-lg px-3 py-2 text-sm"><option value="daily">Daily</option><option value="monthly">Monthly</option></select><input id="dateSelect" type="date" class="border rounded-lg px-3 py-2 text-sm"><input id="monthSelect" type="month" class="hidden border rounded-lg px-3 py-2 text-sm"><button id="viewBtn" class="bg-blue-600 text-white rounded-lg px-4 py-2 text-sm font-bold">View</button></div></div>
<div class="bg-white border rounded-xl"><div id="printable" class="p-5"><div class="border-b-2 border-emerald-600 pb-4 mb-4"><div class="flex flex-wrap justify-between gap-3"><div><h2 id="plantTitle" class="text-2xl font-black">--</h2><p id="serviceLine" class="text-sm font-bold text-emerald-700"></p><p class="text-sm text-slate-500 mt-1">Inverter generation with HT/VCB values when available</p></div><div id="status" class="text-xs font-bold text-slate-500 flex gap-2 items-center"><span class="status-dot bg-slate-400"></span>Waiting</div></div><div class="grid sm:grid-cols-3 gap-3 mt-4 bg-slate-50 rounded-lg p-3 text-sm"><div><span class="block text-[10px] uppercase font-black text-slate-400">Location</span><span id="location">--</span></div><div><span class="block text-[10px] uppercase font-black text-slate-400">Capacity</span><span id="capacity">--</span></div><div><span class="block text-[10px] uppercase font-black text-slate-400">Period</span><span id="period">--</span></div></div></div><div id="htNote" class="hidden mb-3 rounded-lg bg-amber-50 border border-amber-200 px-3 py-2 text-xs font-bold text-amber-800">HT/VCB telemetry is not available for this period. Inverter data remains valid; HT columns are shown as --.</div><div class="wrap"><table class="tbl"><thead id="head"></thead><tbody id="body"><tr><td class="py-10 text-slate-400">Loading...</td></tr></tbody></table></div></div></div></section></main></div>
<script>
const catalog=<?php echo json_encode($catalog,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES); ?>;const role=<?php echo json_encode($userRole); ?>;const assigned=<?php echo json_encode($userPlant); ?>;const initial=<?php echo json_encode($selectedPlant); ?>;const token=new URLSearchParams(location.search).get('token')||sessionStorage.getItem('vs_token')||localStorage.getItem('vs_token')||'';
const plantSelect=document.getElementById('plantSelect'),typeSelect=document.getElementById('typeSelect'),dateSelect=document.getElementById('dateSelect'),monthSelect=document.getElementById('monthSelect');let report=null,ws=null,liveInv={},liveVcb=null,refreshTimer=null;
function parts(){const o={};new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Kolkata',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}).formatToParts(new Date()).forEach(p=>{if(p.type!=='literal')o[p.type]=p.value});return o}function today(){const p=parts();return `${p.year}-${p.month}-${p.day}`}function month(){return today().slice(0,7)}function quarter(){const p=parts();return `${p.hour}:${String(Math.floor(Number(p.minute)/15)*15).padStart(2,'0')}`}function f(v){const n=Number(v);return Number.isFinite(n)?n.toFixed(2):'--'}function esc(x){return String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function init(){if(role==='admin')plantSelect.add(new Option('All Plants','all'));Object.values(catalog).forEach(p=>{if(role==='admin'||p.id===assigned)plantSelect.add(new Option(p.name,p.id))});plantSelect.value=[...plantSelect.options].some(o=>o.value===initial)?initial:(role==='admin'?'vinoba-1':assigned);if(role!=='admin')plantSelect.classList.add('hidden');dateSelect.value=today();monthSelect.value=month();header();toggle();fetchReport();}
function header(){const id=plantSelect.value,p=catalog[id];document.getElementById('plantTitle').textContent=id==='all'?'ALL PLANTS':p.name.toUpperCase();document.getElementById('serviceLine').textContent=id==='all'?'Service Numbers: 06914430133 / 06914430134':'Service Number - '+p.service_number;document.getElementById('location').textContent=id==='all'?'Multiple Sites':p.location;document.getElementById('capacity').textContent=id==='all'?Object.values(catalog).reduce((s,x)=>s+Number(x.capacity||0),0)+' MW':p.capacity+' MW';}
function toggle(){const m=typeSelect.value==='monthly';dateSelect.classList.toggle('hidden',m);monthSelect.classList.toggle('hidden',!m);if(m){closeWS();clearInterval(refreshTimer);refreshTimer=null}else{connectWS();if(!refreshTimer)refreshTimer=setInterval(fetchReport,30000)}}
function setStatus(t,k='normal'){document.getElementById('status').innerHTML=`<span class="status-dot ${k==='live'?'bg-emerald-500':k==='error'?'bg-red-500':'bg-slate-400'}"></span>${esc(t)}`}
async function fetchReport(){const type=typeSelect.value,period=type==='daily'?dateSelect.value:monthSelect.value,plant=plantSelect.value;if(!period)return;document.getElementById('period').textContent=period;try{const q=new URLSearchParams({tab:'inv_vcb',type,date:period,plant});if(token)q.set('token',token);const r=await fetch('api_reports.php?'+q,{cache:'no-store',headers:token?{'Authorization':'Bearer '+token}:{}});const j=await r.json();if(!j.success)throw new Error(j.error||'Report failed');report=j;mergeLive();render();setStatus((j.meta?.source==='db_live'?'Live database':'Report database')+' • '+(j.meta?.generated_at||''),j.meta?.source==='db_live'?'live':'normal');const b=document.getElementById('jsonBtn');b.disabled=false;b.classList.remove('opacity-50');}catch(e){setStatus(e.message,'error');document.getElementById('body').innerHTML=`<tr><td class="py-10 text-red-600 font-bold">${esc(e.message)}</td></tr>`}}
function mergeLive(){if(!report||typeSelect.value!=='daily'||dateSelect.value!==today()||plantSelect.value==='all')return;const rows=report.data||[],names=report.meta.inv_names||[];Object.keys(liveInv).forEach(n=>{if(!names.includes(n)){names.push(n);const i=names.length;rows.forEach(r=>{r['inv'+i+'_kwh']=0;r['inv'+i+'_kw']=0})}});const row=rows.find(r=>r.time_label===quarter());if(!row)return;Object.entries(liveInv).forEach(([n,v])=>{const i=names.indexOf(n)+1;row['inv'+i+'_kwh']=Number(v.kwh||0);row['inv'+i+'_kw']=Number(v.kw||0)});row.inv_total_kwh=names.reduce((s,_,i)=>s+Number(row['inv'+(i+1)+'_kwh']||0),0);row.inv_total_kw=names.reduce((s,_,i)=>s+Number(row['inv'+(i+1)+'_kw']||0),0);if(liveVcb!==null){row.vcb_kwh=liveVcb;report.meta.ht_available=true;row.tx_loss=row.inv_total_kwh-row.vcb_kwh}}
function render(){const names=report.meta.inv_names||[],ht=!!report.meta.ht_available;document.getElementById('htNote').classList.toggle('hidden',ht);let h='<tr><th>Time / Date</th>';names.forEach(n=>h+=`<th>${esc(n)} kWh</th><th>${esc(n)} kW</th>`);h+='<th>Inv Total kWh</th><th>Inv Total kW</th><th>HT/VCB kWh</th><th>HT/VCB kW</th><th>TX Loss</th></tr>';document.getElementById('head').innerHTML=h;document.getElementById('body').innerHTML=(report.data||[]).map(r=>{let x=`<tr><td class="font-bold">${esc(r.time_label)}</td>`;names.forEach((_,i)=>x+=`<td>${f(r['inv'+(i+1)+'_kwh'])}</td><td>${f(r['inv'+(i+1)+'_kw'])}</td>`);x+=`<td class="font-bold">${f(r.inv_total_kwh)}</td><td class="font-bold">${f(r.inv_total_kw)}</td><td>${ht?f(r.vcb_kwh):'--'}</td><td>${ht?f(r.vcb_kw):'--'}</td><td>${ht&&r.tx_loss!==null?f(r.tx_loss):'--'}</td></tr>`;return x}).join('')||'<tr><td>No data</td></tr>';}
function connectWS(){closeWS();if(typeSelect.value!=='daily'||dateSelect.value!==today()||plantSelect.value==='all')return;const plant=plantSelect.value;try{ws=new WebSocket('wss://vinobasolar.scadahub.in:5001');ws.onopen=()=>ws.send(JSON.stringify({type:'subscribe',unit_id:plant}));ws.onmessage=e=>{try{const d=JSON.parse(e.data);if(d.unit_id!==plant)return;const vals=d.values||{},task=String(d.task||'').toLowerCase(),dev=String(d.device||'');if(task==='inverter'||dev.toLowerCase().includes('inverter')){let kwh=null,kw=null;for(const [k,v] of Object.entries(vals)){if(kwh===null&&/daily.*generation|daily.*gen/i.test(k))kwh=Number(v)||0;if(kw===null&&/active.*power|ac.*power|power.*ac/i.test(k)&&!/reactive|apparent|3.phase/i.test(k))kw=Number(v)||0}liveInv[dev||'Inverter']={kwh:kwh??liveInv[dev]?.kwh??0,kw:kw??liveInv[dev]?.kw??0};}const tags=d.virtualTags||{};for(const [k,v] of Object.entries(tags))if(/vcb.*today|today.*energy/i.test(k)){liveVcb=Number(typeof v==='object'?v.value:v)||0;break}mergeLive();render();}catch(_){}};ws.onclose=()=>setTimeout(connectWS,5000)}catch(_){}}
function closeWS(){if(ws){try{ws.close()}catch(_){}ws=null}liveInv={};liveVcb=null}
function downloadJson(){if(!report)return;const blob=new Blob([JSON.stringify(report,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`report-${plantSelect.value}-${typeSelect.value}.json`;a.click();URL.revokeObjectURL(a.href)}
function exportPDF(){const el=document.getElementById('printable');el.classList.add('pdf-mode');html2pdf().set({margin:5,filename:`report-${plantSelect.value}.pdf`,html2canvas:{scale:1.5},jsPDF:{orientation:'landscape',unit:'mm',format:'a4'}}).from(el).save().finally(()=>el.classList.remove('pdf-mode'))}
fetch('sidebar.html',{cache:'no-store'}).then(r=>r.text()).then(h=>{document.getElementById('sidebar-container').innerHTML=h});plantSelect.addEventListener('change',()=>{header();connectWS();fetchReport()});typeSelect.addEventListener('change',()=>{toggle();fetchReport()});dateSelect.addEventListener('change',()=>{connectWS();fetchReport()});monthSelect.addEventListener('change',fetchReport);document.getElementById('viewBtn').addEventListener('click',fetchReport);init();
</script></body></html>
