<?php require 'check_auth.php'; ?>
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title id="pageTitle">Solar Plant - VCB</title>
<script src="https://cdn.tailwindcss.com"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
<script src="sidebar-control.js?v=8" defer></script>
<style>::-webkit-scrollbar{width:8px;height:8px}::-webkit-scrollbar-track{background:#f8fafc}::-webkit-scrollbar-thumb{background:#cbd5e1;border-radius:4px}::-webkit-scrollbar-thumb:hover{background:#94a3b8}</style>
</head>
<body class="h-full bg-slate-50 text-slate-800 font-sans">
<div class="min-h-screen flex relative">
<div id="overlay" class="fixed inset-0 bg-slate-900 bg-opacity-40 hidden z-30 md:hidden transition-opacity"></div>
<div id="sidebar-container"></div>
<main class="flex-1 flex flex-col w-full md:ml-64 overflow-x-hidden">
<header class="bg-white p-4 sm:px-6 flex justify-between items-center sticky top-0 z-20 border-b border-slate-200 shadow-sm">
<div class="flex items-center gap-3"><button id="menuBtn" class="md:hidden text-emerald-600 text-2xl focus:outline-none">&#9776;</button><div><h2 class="text-xl font-black text-slate-800 tracking-tight">VCB Panel Status</h2><p class="text-xs text-slate-500 hidden sm:block">HT panel electrical parameters</p></div></div>
<div class="flex items-center gap-3 bg-slate-50 px-3 py-1.5 rounded-lg border border-slate-100"><div id="refreshPulse" class="w-2.5 h-2.5 bg-slate-400 rounded-full"></div><span id="liveText" class="text-[10px] font-bold text-slate-500 hidden sm:inline">CONNECTING</span><span class="text-xs font-bold text-slate-600 tracking-widest hidden sm:inline border-l border-slate-200 pl-3" id="clockDisplay">--:--:--</span></div>
</header>
<div class="p-4 sm:p-6 w-full flex flex-col gap-6 max-w-[1600px] mx-auto">
<div class="grid grid-cols-1 md:grid-cols-4 gap-4 sm:gap-6">
<div class="bg-white rounded-xl shadow-sm border border-slate-200 p-5 relative overflow-hidden"><div class="absolute -right-4 -top-4 w-24 h-24 bg-emerald-50 rounded-full blur-xl -z-10"></div><h3 class="text-[10px] font-black text-slate-400 uppercase tracking-widest mb-2">VCB Status</h3><p class="font-black text-slate-500 text-3xl" id="vcb_status">--</p><p class="text-xs text-slate-500 font-medium mt-1">Circuit breaker / export status</p></div>
<div class="bg-white rounded-xl shadow-sm border border-slate-200 p-5 relative overflow-hidden"><div class="absolute -right-4 -top-4 w-24 h-24 bg-blue-50 rounded-full blur-xl -z-10"></div><h3 class="text-[10px] font-black text-slate-400 uppercase tracking-widest mb-2">3-Phase Active Power</h3><p class="font-black text-slate-800 text-3xl" id="vcb_load">-- <span class="text-sm font-bold text-blue-600">kW</span></p><p class="text-xs text-slate-500 font-medium mt-1">Current export</p></div>
<div class="bg-white rounded-xl shadow-sm border border-slate-200 p-5 relative overflow-hidden"><div class="absolute -right-4 -top-4 w-24 h-24 bg-purple-50 rounded-full blur-xl -z-10"></div><h3 class="text-[10px] font-black text-slate-400 uppercase tracking-widest mb-2">Today Energy</h3><p class="font-black text-slate-800 text-3xl" id="vcb_today">-- <span class="text-sm font-bold text-purple-600">kWh</span></p><p class="text-xs text-slate-500 font-medium mt-1">Today's HT export energy</p></div>
<div class="bg-white rounded-xl shadow-sm border border-slate-200 p-5 relative overflow-hidden"><div class="absolute -right-4 -top-4 w-24 h-24 bg-orange-50 rounded-full blur-xl -z-10"></div><h3 class="text-[10px] font-black text-slate-400 uppercase tracking-widest mb-2">Frequency</h3><p class="font-black text-slate-800 text-3xl" id="vcb_freq">-- <span class="text-sm font-bold text-orange-600">Hz</span></p><p class="text-xs text-slate-500 font-medium mt-1">Grid frequency</p></div>
</div>
<div class="bg-white rounded-xl shadow-sm border border-slate-200 p-5"><h3 class="text-sm font-black text-slate-600 uppercase tracking-widest mb-4">3-Phase Voltages</h3><div class="grid gap-4 md:grid-cols-3">
<div class="bg-slate-50 rounded-lg p-4 border border-slate-100 text-center"><p class="text-[10px] font-bold text-slate-400 uppercase tracking-wider">R Phase-N</p><p class="mt-3 text-2xl font-black text-slate-800" id="v_r">-- <span class="text-sm font-bold text-slate-500">V</span></p></div><div class="bg-slate-50 rounded-lg p-4 border border-slate-100 text-center"><p class="text-[10px] font-bold text-slate-400 uppercase tracking-wider">Y Phase-N</p><p class="mt-3 text-2xl font-black text-slate-800" id="v_y">-- <span class="text-sm font-bold text-slate-500">V</span></p></div><div class="bg-slate-50 rounded-lg p-4 border border-slate-100 text-center"><p class="text-[10px] font-bold text-slate-400 uppercase tracking-wider">B Phase-N</p><p class="mt-3 text-2xl font-black text-slate-800" id="v_b">-- <span class="text-sm font-bold text-slate-500">V</span></p></div><div class="bg-slate-50 rounded-lg p-4 border border-slate-100 text-center"><p class="text-[10px] font-bold text-slate-400 uppercase tracking-wider">V12 (RY)</p><p class="mt-3 text-2xl font-black text-slate-800" id="v_ry">-- <span class="text-sm font-bold text-slate-500">V</span></p></div><div class="bg-slate-50 rounded-lg p-4 border border-slate-100 text-center"><p class="text-[10px] font-bold text-slate-400 uppercase tracking-wider">V23 (YB)</p><p class="mt-3 text-2xl font-black text-slate-800" id="v_yb">-- <span class="text-sm font-bold text-slate-500">V</span></p></div><div class="bg-slate-50 rounded-lg p-4 border border-slate-100 text-center"><p class="text-[10px] font-bold text-slate-400 uppercase tracking-wider">V31 (BR)</p><p class="mt-3 text-2xl font-black text-slate-800" id="v_br">-- <span class="text-sm font-bold text-slate-500">V</span></p></div>
</div></div>
<div class="grid grid-cols-1 lg:grid-cols-2 gap-6">
<div class="bg-white rounded-xl shadow-sm border border-slate-200 p-5"><h3 class="text-sm font-black text-slate-600 uppercase tracking-widest mb-4">Phase Currents &amp; Power</h3><div class="grid gap-3 sm:grid-cols-3"><div class="bg-slate-50 rounded-lg p-4 border border-slate-100 text-center"><p class="text-[10px] font-bold text-slate-400 uppercase tracking-wider">L1 (R)</p><p class="mt-2 text-xl font-black text-slate-800" id="i_r">-- <span class="text-xs text-slate-500">A</span></p></div><div class="bg-slate-50 rounded-lg p-4 border border-slate-100 text-center"><p class="text-[10px] font-bold text-slate-400 uppercase tracking-wider">L2 (Y)</p><p class="mt-2 text-xl font-black text-slate-800" id="i_y">-- <span class="text-xs text-slate-500">A</span></p></div><div class="bg-slate-50 rounded-lg p-4 border border-slate-100 text-center"><p class="text-[10px] font-bold text-slate-400 uppercase tracking-wider">L3 (B)</p><p class="mt-2 text-xl font-black text-slate-800" id="i_b">-- <span class="text-xs text-slate-500">A</span></p></div></div><div class="grid gap-3 sm:grid-cols-3 mt-3"><div class="bg-slate-50 rounded-lg p-4 border border-slate-100 text-center"><p class="text-[10px] font-bold text-slate-400 uppercase tracking-wider">Active Power R</p><p class="mt-2 text-xl font-black text-slate-800" id="p_r">-- <span class="text-xs text-slate-500">kW</span></p></div><div class="bg-slate-50 rounded-lg p-4 border border-slate-100 text-center"><p class="text-[10px] font-bold text-slate-400 uppercase tracking-wider">Active Power Y</p><p class="mt-2 text-xl font-black text-slate-800" id="p_y">-- <span class="text-xs text-slate-500">kW</span></p></div><div class="bg-slate-50 rounded-lg p-4 border border-slate-100 text-center"><p class="text-[10px] font-bold text-slate-400 uppercase tracking-wider">Active Power B</p><p class="mt-2 text-xl font-black text-slate-800" id="p_b">-- <span class="text-xs text-slate-500">kW</span></p></div></div></div>
<div class="bg-white rounded-xl shadow-sm border border-slate-200 p-5"><h3 class="text-sm font-black text-slate-600 uppercase tracking-widest mb-4">Power Factor &amp; THD</h3><div class="grid gap-3 sm:grid-cols-3"><div class="bg-slate-50 rounded-lg p-4 border border-slate-100 text-center"><p class="text-[10px] font-bold text-slate-400 uppercase tracking-wider">Q1 PF</p><p class="mt-2 text-xl font-black text-slate-800" id="pf_q1">--</p></div><div class="bg-slate-50 rounded-lg p-4 border border-slate-100 text-center"><p class="text-[10px] font-bold text-slate-400 uppercase tracking-wider">Q2 PF</p><p class="mt-2 text-xl font-black text-slate-800" id="pf_q2">--</p></div><div class="bg-slate-50 rounded-lg p-4 border border-slate-100 text-center"><p class="text-[10px] font-bold text-slate-400 uppercase tracking-wider">Q3 PF</p><p class="mt-2 text-xl font-black text-slate-800" id="pf_q3">--</p></div></div><div class="grid gap-3 sm:grid-cols-3 mt-3"><div class="bg-slate-50 rounded-lg p-4 border border-slate-100 text-center"><p class="text-[10px] font-bold text-slate-400 uppercase tracking-wider">Voltage THD R</p><p class="mt-2 text-xl font-black text-slate-800" id="vthd_r">-- <span class="text-xs text-slate-500">%</span></p></div><div class="bg-slate-50 rounded-lg p-4 border border-slate-100 text-center"><p class="text-[10px] font-bold text-slate-400 uppercase tracking-wider">Voltage THD Y</p><p class="mt-2 text-xl font-black text-slate-800" id="vthd_y">-- <span class="text-xs text-slate-500">%</span></p></div><div class="bg-slate-50 rounded-lg p-4 border border-slate-100 text-center"><p class="text-[10px] font-bold text-slate-400 uppercase tracking-wider">Voltage THD B</p><p class="mt-2 text-xl font-black text-slate-800" id="vthd_b">-- <span class="text-xs text-slate-500">%</span></p></div></div></div>
</div>
<div class="bg-white rounded-xl shadow-sm border border-slate-200 p-5"><h3 class="text-sm font-black text-slate-600 uppercase tracking-widest mb-4">Energy &amp; Reactive Power</h3><div class="grid gap-4 md:grid-cols-4"><div class="bg-slate-50 rounded-lg p-4 border border-slate-100 text-center"><p class="text-[10px] font-bold text-slate-400 uppercase tracking-wider">Active Total Export</p><p class="mt-2 text-xl font-black text-slate-800" id="act_exp">-- <span class="text-xs text-slate-500">kWh</span></p></div><div class="bg-slate-50 rounded-lg p-4 border border-slate-100 text-center"><p class="text-[10px] font-bold text-slate-400 uppercase tracking-wider">Active Total Import</p><p class="mt-2 text-xl font-black text-slate-800" id="act_imp">-- <span class="text-xs text-slate-500">kWh</span></p></div><div class="bg-slate-50 rounded-lg p-4 border border-slate-100 text-center"><p class="text-[10px] font-bold text-slate-400 uppercase tracking-wider">Reactive Import</p><p class="mt-2 text-xl font-black text-slate-800" id="react_imp">-- <span class="text-xs text-slate-500">kVAR</span></p></div><div class="bg-slate-50 rounded-lg p-4 border border-slate-100 text-center"><p class="text-[10px] font-bold text-slate-400 uppercase tracking-wider">Reactive Export</p><p class="mt-2 text-xl font-black text-slate-800" id="react_exp">-- <span class="text-xs text-slate-500">kVAR</span></p></div></div></div>
</div>
</main>
</div>
<script>
const params=new URLSearchParams(location.search);const currentPlant=params.get('plant')||'vinoba-1';const plantNames={'vinoba-1':'Vinoba Renewable Energy Private Limited','ssv':'SSV Green Power Private Limited'};document.getElementById('pageTitle').textContent=(plantNames[currentPlant]||currentPlant)+' - VCB';function tick(){document.getElementById('clockDisplay').textContent=new Date().toLocaleTimeString('en-IN',{hour12:false})}tick();setInterval(tick,1000);function num(v){const n=Number(v);return Number.isFinite(n)?n:null}function setMetric(id,value,unit='',digits=2){const el=document.getElementById(id);if(!el)return;const n=num(value);el.innerHTML=(n===null?'--':n.toFixed(digits))+(unit?` <span class="text-xs text-slate-500">${unit}</span>`:'')}function vcbToday(d){for(const [k,x] of Object.entries(d.virtualTags||{}))if(/vcb.*today|today.*energy/i.test(k)){const n=num(x&&typeof x==='object'?x.value:x);if(n!==null)return n}return null}function isVcb(d){const task=String(d.task||'').toLowerCase(),dev=String(d.device||'').toLowerCase(),v=d.values||{};return task==='vcb'||dev.includes('vcb')||(v['3 Phase Active Power']!==undefined&&(v['R Phase-N Voltage']!==undefined||v['Active Total Export']!==undefined))}function setLive(mode){const dot=document.getElementById('refreshPulse'),text=document.getElementById('liveText');if(mode==='live'){dot.className='w-2.5 h-2.5 bg-emerald-500 rounded-full animate-pulse shadow-[0_0_8px_rgba(34,197,94,.6)]';text.textContent='LIVE WEBSOCKET';text.className='text-[10px] font-bold text-emerald-600 hidden sm:inline'}else{dot.className='w-2.5 h-2.5 bg-red-500 rounded-full';text.textContent='RECONNECTING';text.className='text-[10px] font-bold text-red-600 hidden sm:inline'}}
function handleLive(d){if(!d||d.unit_id!==currentPlant||!isVcb(d)||!d.values)return;setLive('live');const v=d.values,p=num(v['3 Phase Active Power'])??0,status=document.getElementById('vcb_status');status.textContent=p>0?'Online':'Standby';status.className='font-black text-3xl '+(p>0?'text-emerald-700':'text-slate-500');setMetric('vcb_load',p,'kW',2);setMetric('vcb_today',vcbToday(d),'kWh',2);setMetric('vcb_freq',v['Frequency (Hz)'],'Hz',2);const map={v_r:['R Phase-N Voltage','V',1],v_y:['Y Phase-N Voltage','V',1],v_b:['B Phase-N Voltage','V',1],v_ry:['V12 (RY)','V',1],v_yb:['V23 (YB)','V',1],v_br:['V31 (BR)','V',1],i_r:['L1 (R)','A',2],i_y:['L2 (Y)','A',2],i_b:['L3 (B)','A',2],p_r:['Active Power R','kW',2],p_y:['Active Power Y','kW',2],p_b:['Active Power B','kW',2],pf_q1:['Q1 PF','',3],pf_q2:['Q2 PF','',3],pf_q3:['Q3 PF','',3],vthd_r:['Voltage THD R','%',2],vthd_y:['Voltage THD Y','%',2],vthd_b:['Voltage THD B','%',2],act_exp:['Active Total Export','kWh',2],act_imp:['Active Total Import','kWh',2],react_imp:['Reactive Import (Q1+Q2)','kVAR',2],react_exp:['Reactive Export (Q3+Q4)','kVAR',2]};Object.entries(map).forEach(([id,s])=>setMetric(id,v[s[0]],s[1],s[2]))}window.handleLive=handleLive;let ws=null,timer=null;function connect(){if(ws&&(ws.readyState===0||ws.readyState===1))return;try{ws=new WebSocket('wss://vinobasolar.scadahub.in:5001');ws.onopen=()=>{setLive('live');ws.send(JSON.stringify({type:'subscribe',unit_id:currentPlant}))};ws.onmessage=e=>{try{handleLive(JSON.parse(e.data))}catch(_){}};ws.onclose=()=>{ws=null;setLive('error');clearTimeout(timer);timer=setTimeout(connect,3000)};ws.onerror=()=>{try{ws.close()}catch(_){}}}catch(_){timer=setTimeout(connect,3000)}}connect();
</script>
</body>
</html>
